 
code: 500
menssage: my custom error at [0] with "aaaa"
args:
{
	"arg1":	"aaaa",
	"path":	[0],
	"value":	["aaaaaa"],
	"type":	"array"
}
